# Generated by Django 3.2.25 on 2025-11-20 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("access", "0020_accesscontrolleddevice_post_to_slack"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterlockReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interlock_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="access.interlock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interlock_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interlock Reservation",
                "verbose_name_plural": "Interlock Reservations",
                "ordering": ["start_time"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "interlock-reservation"
                ),
                models.Model,
            ),
        ),
    ]
